name: Create Yearly Folders

on:
  schedule:
    - cron: '0 0 1 9 *'  # Runs at midnight on the first of September every year
  workflow_dispatch:

jobs:
  create-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create year folder and subfolders with .gitkeep
        run: |
          YEAR=$(date +%Y)
          mkdir -p $YEAR
          
          # Main folders
          MAIN_FOLDERS=(C Python PHP Java Javascript Typescript CPP CSharp Rust Kotlin Dart Fortran Forth Lisp Julia Mojo Bend Zig Crystal CUDA Assembly Shell Swift Go Scala Perl Ruby HTML CSS)
          for folder in "${MAIN_FOLDERS[@]}"; do
            mkdir -p $YEAR/$folder
            touch $YEAR/$folder/.gitkeep
          done

          # Subfolders a-z
          for folder in "${MAIN_FOLDERS[@]}"; do
            for i in {a..z}; do
              mkdir -p $YEAR/$folder/$i
              touch $YEAR/$folder/$i/.gitkeep
            done
          done

          # Subfolders 0-9 and other characters
          for folder in "${MAIN_FOLDERS[@]}"; do
            for i in {0..9}; do
              mkdir -p $YEAR/$folder/$i
              touch $YEAR/$folder/$i/.gitkeep
            done
            mkdir -p $YEAR/$folder/@
            touch $YEAR/$folder/@/.gitkeep
          done

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Create folders and .gitkeep files for $YEAR"
          git push